language: cpp
compiler:
  - gcc
branches:
  only:
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive-full
  - mkdir -p ~/.fonts/
  - cp -rf fonts/* ~/.fonts/
  - sudo fc-cache -f -v
script:
  - latexmk -pdf -e '$pdflatex=q/xelatex %O %S/' main.tex
